"""State management for the LangGraph orchestrator."""

from typing import List, TypedDict
from langchain_core.documents import Document

class GraphState(TypedDict):
    """
    Represents the shared memory payload of our LangGraph system.
    Every node in the graph will read from and write to this dictionary.
    
    Attributes:
        question: The user's original query.
        context: The document chunks retrieved from Qdrant.
        answer: The final response generated by the LLM.
    """
    question: str
    context: List[Document]
    answer: str